import React from "react"
const PrivacyPolicy = () => {
    return (
        <div class="container" style={{padding: "24px"}}>
            <div class="row">
                <div style={{padding: "0px 24px"}}>
                    <p>Gentile Cliente,</p>
                    <p>in ottemperanza agli obblighi previsti dal Regolamento Europeo n. UE/2016/679 (GDPR) e dal D.lgs. n. 101 del 2018 con la presente intendiamo informarLa che Prestige Group S.r.l., con sede in Via Putignani 152 BARI Italia, Partita Iva 12887481005, successivamente denominato anche "Titolare del Trattamento”, in qualità di Titolare sottoporrà a trattamento i dati personali che La riguardano e che ci sono stati o ci potranno venire - da Lei o da altri soggetti – conferiti/comunicati&nbsp; nel corso del rapporto con la nostra struttura.</p><p>Il trattamento dei dati, da Lei liberamente conferiti o in altro modo raccolti, sarà effettuato nel rispetto delle norme privacy in vigore; improntato ai principi di correttezza, liceità e trasparenza e svolto nell’osservanza dei principi di pertinenza, completezza e non eccedenza.</p>
                    <p>I dati saranno raccolti e registrati per le sole finalità di cui al punto 1. saranno conservati per tali scopi per un periodo non superiore a 10 anni dalla loro raccolta a.; per gli altri punti da b. a l.&nbsp; i dati saranno conservati per un tempo massimo di 1 anno.</p><p>Pertanto, secondo quanto previsto dall'articolo 13. del Regolamento Europeo Privacy UE/2016/679 (GDPR) e del D.lgs. 101/18, La informiamo che:</p>
                    <ol>
                        <li>I dati da Lei forniti verranno trattati per le seguenti finalità:</li>
                        <li>a. Per il regolare svolgimento delle attività istituzionali previste dall’oggetto sociale:</li>
                        <li>b. Per esigenze relative alla stipula di contratti e incarichi, alla relativa esecuzione, alle successive modifiche o variazioni e per qualsiasi obbligazione prevista per l’adempimento degli stessi.</li> <li>c. Per esigenze di tipo operativo, organizzativo, gestionale, fiscale, finanziario, assicurativo e contabile relative al rapporto contrattuale e/o precontrattuale instaurato.</li>
                        <li>d. Per adempiere a qualunque tipo di obbligo previsto da leggi, regolamenti o normativa comunitaria.</li> <li>e. Per la registrazione, gestione e conservazione dei log di eventuali accessi al Sito Web aziendale, al Sistema Informativo Aziendale e alle sedi aziendali.</li> <li>f. Per fini di Controllo Accessi, Sicurezza Aziendale e Videosorveglianza.</li> <li>g. Per esigenze di monitoraggio delle modalità di erogazione di prodotti/servizi, dell’andamento delle relazioni con i fornitori e dell’analisi e della gestione dei rischi connessi al rapporto contrattuale.</li>
                        <li>h. Per attività di marketing tradizionale quali: invio di brochure, cataloghi e documentazione commerciale e/o tecnica con posta cartacea e telefonate con operatore (previa acquisizione di Suo esplicito consenso).</li> <li>i. Per attività di marketing con strumenti automatizzati o assimilati quali: Fax, E-mail, SMS, MMS, Istant Messaging, Chat e telefonate senza operatore (previa acquisizione di esplicito consenso da parte Sua);</li>
                        <li>l. Per attività di marketing on-line, web marketing e web advertising (previa acquisizione di Suo esplicito consenso).</li>
                    </ol>
                    <p>&nbsp;</p>
                    <p>In tal caso, Lei ha il diritto di non essere sottoposto a una decisione basata unicamente su un trattamento automatizzato e pertanto potrà in qualsiasi momento richiedere e ottenere l'intervento umano da parte del Titolare del Trattamento, esprimere la propria opinione e contestare la decisione finale presa.&nbsp;</p>
                    <ol >
                        <li>Il trattamento sarà effettuato in maniera:</li>
                    </ol>
                    <ul>
                        <li>Interamente automatizzata.</li>
                    </ul>
                    <p>&nbsp;</p>
                    <p>Il trattamento potrà consistere nelle seguenti operazioni:</p>
                    <p>Raccolta, registrazione, organizzazione e conservazione; Consultazione e utilizzo; Elaborazione, modificazione; selezione, estrazione, raffronto; Interconnessione; trasmissione e comunicazione; diffusione; cancellazione e distruzione; blocco e limitazione.</p>
                    <p>Il trattamento sarà effettuato sia con l’utilizzo di supporti cartacei che con l’ausilio di strumenti elettronici, informatici e telematici idonei a garantire la sicurezza e la riservatezza dei dati stessi in conformità a quanto stabilito dall’art. 32. del Regolamento Europeo Privacy UE/2016/679 (GDPR).</p>
                    <p>Nello svolgimento delle operazioni di trattamento saranno, comunque, sempre adottate tutte le misure tecniche, informatiche, organizzative, logistiche e procedurali di sicurezza in modo che sia garantito il livello adeguato di protezione dei dati previsto dalla legge. Le metodologie su menzionate, applicate per il trattamento, garantiranno l’accesso ai dati ai soli soggetti specificati ai punti 4. e 5.</p>
                    <p>“Per poter offrire all'utente i metodi di pagamento di Klarna, al checkout potremmo trasmettere a Klarna i dati personali dell'utente sotto forma di recapiti e dettagli dell'ordine, in modo che Klarna possa valutare l'idoneità dell'utente ai suoi metodi di pagamento e personalizzare tali metodi di pagamento. I dati personali dell'utente trasferiti sono trattati in linea con<a href="https://www.klarna.com/international/privacy-policy/" target="_blank" rel="noopener noreferrer"> la policy sulla privacy di Klarna.</a>”</p><p>&nbsp;</p><ol start="3"><li>Il conferimento dei dati</li>
                    </ol>
                    <p>o&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; obbligatorio e non necessita del Suo consenso per il raggiungimento di finalità connesse ad obblighi previsti da leggi, regolamenti o normative comunitarie;</p>
                    <p>o&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; indispensabile e non necessita del suo consenso per tutti i dati personali imprescindibili per una corretta instaurazione, gestione e prosecuzione del rapporto commerciale e/o contrattuale;</p>
                    <p>o&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; indispensabile e non necessita del Suo consenso per la salvaguardia degli interessi vitali di una persona fisica;</p><p>o&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; indispensabile e non necessita del Suo consenso per l'esecuzione di compiti di interesse pubblico o esercizio di pubblici poteri di cui siamo stati investiti;</p><p>o&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; indispensabile e non necessita del Suo consenso per il perseguimento dei seguenti legittimi interessi aziendali o di soggetti terzi ;</p>
                    <p>o&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; facoltativo e necessita del Suo esplicito consenso per tutti i dati personali raccolti per finalità non direttamente e/o indirettamente connesse ad obblighi contrattuali, precontrattuali, di legge, di salvaguardia di interessi vitali, di svolgimento di compiti pubblici, di esercizio di pubblici poteri o di perseguimento di legittimi interessi.</p><p>&nbsp;</p><p>Un eventuale rifiuto, seppur legittimo, a fornire in tutto o in parte i dati di cui sopra, potrebbe compromettere il regolare svolgimento del rapporto con la nostra struttura ed in particolare, per i dati personali su definiti come obbligatori e indispensabili, potrebbe comportare l’impossibilità da parte nostra di effettuare il normale svolgimento delle operazioni aziendali e la regolare erogazione dei prodotti/servizi richiesti.</p>
                    <p>&nbsp;</p>
                    <ol start="4">
                        <li>I soggetti o le categorie di soggetti che potranno venire conoscenza dei dati o a cui potranno essere comunicati i dati sono i seguenti:</li></ol><ul><li>Rappresentante Legale del Titolare del Trattamento</li>
                    </ul>
                    <p>&nbsp;</p>
                    <p>Responsabili del Trattamento: Consulenti e Società di Consulenza; Agenti e Agenzie di Rappresentanza; Istituti Bancari e Assicurativi; Società di Recupero Crediti; Revisori e Società di Revisione; Studi Commercialisti; Studi di Consulenza del Lavoro; Società di Trasporto e Logistica;</p>
                    <ul>
                        <li>incaricati del Trattamento: Direzione; Amministrazione e Finanza; Commerciale; Logistica; Acquisti; Segreteria; Organizzazione; Assistenza Clienti; Marketing; Vendite; Amministratori di Sistema</li>
                    </ul>
                    <p>I dati personali potranno essere, altresì diffusi, ma solo in forma aggregata, anonima e per finalità statistiche.</p>
                    <p>&nbsp;</p>
                    <ol start="5">
                        <li>Qualora il trattamento potesse riguardare anche dati personali rientranti nel novero dei dati "sensibili" (vale a dire dati idonei a rivelare l'origine razziale ed etnica, le convinzioni religiose, filosofiche o di altro genere, le opinioni politiche, l'adesione a partiti, sindacati, associazioni od organizzazioni a carattere religioso, filosofico, politico o sindacale, nonché i dati personali idonei a rivelare lo stato di salute e la vita sessuale) o “giudiziari” (vale a dire dati idonei a rivelare provvedimenti in materia di casellario giudiziale, di anagrafe delle sanzioni amministrative dipendenti da reato e dei relativi carichi pendenti o la qualità di&nbsp; imputato o di indagato) il trattamento sarà effettuato nei limiti indicati dalle Autorizzazioni Generali del Garante Privacy, secondo le modalità previste dal D.lgs. 101/18 e per le finalità strettamente necessarie al regolare svolgimento dell’attività aziendale, delle operazioni relative all’erogazione di prodotti/servizi e all’adempimento di obblighi contrattuali e/o di legge/regolamento.</li>
                    </ol>
                    <p>In tal caso i soggetti o le categorie di soggetti che potranno venire a conoscenza dei dati sensibili o a cui potranno essere comunicati i dati sono i seguenti:</p>
                    <ul>
                        <li>Rappresentante Legale del Titolare del Trattamento:</li> <li>Responsabili del Trattamento: Istituti Bancari e Assicurativi; Società di Recupero Crediti; Revisori e Società di Revisione; Studi Commercialisti; Studi di Consulenza del Lavoro; Medici e Studi Medici;</li> <li>Incaricati del trattamento: Direzione; Amministrazione e finanza; Amministratori di Sistema;</li></ul><ol start="6"><li>I dati personali potranno, inoltre, essere comunicati a Enti Pubblici, Forze di Polizia o altri Soggetti Pubblici e Privati, ma esclusivamente al fine di adempiere ad obblighi di legge, regolamento o normativa comunitaria.</li>
                    </ol>
                    <p>I dati in questione non saranno comunicati ad altri soggetti oltre a quelli previsti nella presente informativa e i dati idonei a rivelare lo stato di salute dell'interessato non saranno comunque in alcun caso diffusi.</p><ol start="7"><li>I dati trattati potranno essere trattati e trasferiti, per le finalità di cui al punto 1. e secondo le modalità di cui al punto 2., anche a soggetti di cui ai punti 4. e 5. stanziati nei seguenti paesi appartenenti all’Unione Europea: NESSUNO</li></ol><p>e/o al di fuori dell’Unione Europea nei seguenti paesi: NESSUNO</p><p>sulla base di uno dei seguenti presupposti:</p><p>o&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Decisione di Adeguatezza della Commissione Europea;</p><p>o&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Adeguate Garanzie Privacy ;</p>
                    <p>o&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Autorizzazione dell’Autorità Garante Privacy.</p><ol start="8"><li>In ogni caso Lei potrà sempre richiedere in qualsiasi momento al</li></ol><p> Rappresentante Legale del Titolare del trattamento</p><p>info@enjoyricondizionati.it</p><p>copia dei Suoi dati personali, informazioni in merito alla località in cui i Suoi dati personali sono trattati e un elenco aggiornato con gli estremi identificativi&nbsp; di tutti i Responsabili&nbsp; del Trattamento e degli Amministratori di Sistema autorizzati al trattamento dei Suoi dati.</p><p>Ricordiamo che se dovesse riscontrare anomalie o violazioni in merito al trattamento dei suoi dati personali ha il diritto di rivolgersi al Garante per la protezione dei dati personali http://www.garanteprivacy.it oppure al Garante europeo della protezione dei dati utilizzando il seguente link http://www.edps.europa.eu.&nbsp;</p>
                    <ol start="9"><li>La informiamo che nella Sua qualità di interessato, Lei ha, oltre il diritto di proporre reclamo a un’autorità di controllo, i diritti qui sotto elencati, che potrà far valere rivolgendo apposita richiesta al Titolare del trattamento e/o al responsabile del trattamento:</li></ol><p>Art. 15 Diritto di accesso - L’interessato ha il diritto di ottenere dal titolare del trattamento la conferma che sia o meno in corso un trattamento di dati personali che lo riguardano e in tal caso, di ottenere l’accesso ai dati personali e alle informazioni riguardanti il trattamento.</p><p>Art. 16 Diritto di rettifica - L'interessato ha il diritto di ottenere dal titolare del trattamento la rettifica dei dati personali inesatti che lo riguardano senza ingiustificato ritardo. Tenuto conto delle finalità del trattamento, l'interessato ha il diritto di ottenere l'integrazione dei dati personali incompleti, anche fornendo una dichiarazione integrativa.</p>
                    <p>Art. 17 Diritto alla cancellazione (diritto all’oblio) - L'interessato ha il diritto di ottenere dal titolare del trattamento la cancellazione dei dati personali che lo riguardano senza ingiustificato ritardo e il titolare del trattamento ha l'obbligo di cancellare senza ingiustificato ritardo i dati personali.</p><p>Art. 18 Diritto di limitazione del trattamento - L'interessato ha il diritto di ottenere dal titolare del trattamento la limitazione del trattamento quando ricorre una delle seguenti ipotesi:</p>
                    <ol>
                        <li>a. l'interessato contesta l'esattezza dei dati personali, per il periodo necessario al titolare del trattamento per verificare l'esattezza di tali dati personali;</li> <li>b. il trattamento è illecito e l'interessato si oppone alla cancellazione dei dati personali e chiede invece che ne sia limitato l'utilizzo;</li> <li>c. benché il titolare del trattamento non ne abbia più bisogno ai fini del trattamento, i dati personali sono necessari all'interessato per l'accertamento, l'esercizio o la difesa di un diritto in sede giudiziaria;</li>
                        <li>d. l'interessato si è opposto al trattamento ai sensi dell'articolo 21, paragrafo 1 del regolamento, in attesa della verifica in merito all'eventuale prevalenza dei motivi legittimi del titolare del trattamento rispetto a quelli dell'interessato.</li></ol><p>Art. 20 Diritto alla portabilità dei dati - L'interessato ha il diritto di ricevere in un formato strutturato, di uso comune e leggibile da dispositivo automatico i dati personali che lo riguardano forniti a un titolare del trattamento e ha il diritto di trasmettere tali dati a un altro titolare del trattamento senza impedimenti da parte del titolare del trattamento cui li ha forniti.</p><p>Nell'esercitare i propri diritti relativamente alla portabilità dei dati, l'interessato ha il diritto di ottenere la trasmissione diretta dei dati personali da un titolare del trattamento all'altro, se tecnicamente fattibile.</p>
                    <p>Art. 21 Diritto di opposizione - L'interessato ha il diritto di opporsi in qualsiasi momento, per motivi connessi alla sua situazione particolare, al trattamento dei dati personali che lo riguardano compresa la profilazione sulla base di tali disposizioni.</p>
                    <p>Art. 22 Diritto di non essere sottoposto a processo decisionale automatizzato, compresa la profilazione - L'interessato ha il diritto di non essere sottoposto a una decisione basata unicamente sul trattamento automatizzato, compresa la profilazione, che produca effetti giuridici che lo riguardano o che incida in modo analogo significativamente sulla sua persona.</p>
                    <p>&nbsp;</p>
                </div>
            </div>
        </div>
    )
}

export default PrivacyPolicy